// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: plan_country.sql

package db

import (
	"context"
)

const getPlanCountry = `-- name: GetPlanCountry :one
SELECT plan_id, country, price FROM plan_country
WHERE plan_id = $1 AND country = $2 LIMIT 1
`

type GetPlanCountryParams struct {
	PlanID  int64  `json:"plan_id"`
	Country string `json:"country"`
}

func (q *Queries) GetPlanCountry(ctx context.Context, arg GetPlanCountryParams) (PlanCountry, error) {
	row := q.db.QueryRow(ctx, getPlanCountry, arg.PlanID, arg.Country)
	var i PlanCountry
	err := row.Scan(&i.PlanID, &i.Country, &i.Price)
	return i, err
}
