// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: role_permission.sql

package db

import (
	"context"
)

const createRolePermission = `-- name: CreateRolePermission :one
INSERT INTO role_permission (
    role_id, permission_id
) VALUES (
    $1, $2
) RETURNING role_id, permission_id
`

type CreateRolePermissionParams struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, createRolePermission, arg.RoleID, arg.PermissionID)
	var i RolePermission
	err := row.Scan(&i.RoleID, &i.PermissionID)
	return i, err
}
